blog/urls.py
from django.urls import re_path
from .views import index, add_post, post

app_name = "blog"

urlpatterns = [
    # Your code here
    re_path("", index, name="index"),
    re_path("add_post/", add_post, name="addpost"),
    re_path("post/<int:article_id>/", post, name="post"),

]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path

app_name = "my_site"

urlpatterns = [
    re_path("admin/", admin.site.urls),
    re_path("blog/", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models


class Post(models.Model):

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    body = models.TextField()
    date = models.DateTimeField()
    description = models.TextField(max_length=200, default="Description")

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm
from .models import Post


class AddPostForm(ModelForm):
    class Meta(object):
        model = Post
        fields = ["title", "body"]

blog/views.py
# global var
from dotenv import load_dotenv

from .models import Post
from .forms import AddPostForm

from django.shortcuts import render

from requests.exceptions import HTTPError

import datetime
import requests
import os
import datetime


load_dotenv(".env")
API_KEY = os.getenv("API_KEY")
print("apikey ***", API_KEY)

POST = []


def index(request):
    # Your code here
    today = datetime.date.today()

    url = (
        'https://newsapi.org/v2/top-headlines?'
        'country=us&'
        f'from={today}&'  # YYYY-MM-DD
        #    'sortBy=popularity&'
        f'apiKey={API_KEY}')

    print("*******", url)
    print(today)
    articles = []

    try:
        response = requests.get(url)
        if response.status_code == 200:
            r_json: dict = response.json()
            if r_json["totalResults"] != 0:
                # articles = r_json["articles"][:20]
                for index, article in enumerate(r_json["articles"], 1):
                    if article["title"] and article["content"]:
                        article["id"] = index
                        articles.append(article)

                        new_post = Post(
                            title=article["title"],
                            body=article["content"],
                            description=article["description"],
                            date=today
                        )
                        new_post.save()

                    if len(articles) == 20:
                        POST = articles
                        break

        else:
            raise HTTPError(response.status_code)

    except requests.exceptions.RequestException as e:
        # Maneja errores de solicitud y problemas de red aquí
        print(f"Error en la solicitud HTTP: {e}")

    context = {
        "articles": articles,
        "date": today,
    }

    return render(request, "blog.html", context=context)


def post(request, article_id):
    if POST:
        article = POST[article_id]

    else:
        article = Post.objects.get(id=article_id)

    return render(
        request,
        "post.html",
        context={
            "article": article,
            "date": datetime.date.today()
        })


def add_post(request):
    # Your code here
    context = {}
    return render(request, "add_post.html", context)

blog/templates/add_post.html
{% extends "header.html" %}

{# Your code here #}

blog/templates/blog.html
{% extends "header.html" %}
{# Your code here #}
{% block title %}
News
{% endblock title %}

{% block content %}

    <div class="flex">
        {% for art in articles %} 
            <a href="{% url 'blog:post' article_id=art.id  %}" class="box">
                <div >
                    <h2>{{art.id}}</h2>
                    <h3>{{art.title}}</h3>
                    <h5>Date (DD-MM-YYYY):{{date.day}}-{{date.month}}-{{date.year}}</h5>
                    <p>{{art.description}}</p>
                </div>
            </a>
        {% endfor %}
    </div>

{% endblock content %}

blog/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}My site{% endblock title %}</title>
    <meta charset="utf-8" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'css/mystyles.css' %}">
</head>

<body class="body" style="background-color: #f6f6f6">
    <center>
        <h3>My blog</h3>
    </center>
    <br /><br />
    {% block content %} {% endblock %}

    <footer>
        <br />
        <br />
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    {% comment %} <script src=""{% static 'script/script.js' %}""></script> {% endcomment %}
</body>

</html>

blog/templates/post.html
{% extends "header.html" %}

{# Your code here #}
{% block content %}hello{% endblock content %}